//  Manuel Perez 263130 -  Marcos Darricarrere 254937

package Interfaz;

import Dominio.*;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;

public class VentanaMenu extends javax.swing.JFrame {
    private Empresa empresa;
    private int[][] matrizFumigacion = new int[15][50];
    
    public VentanaMenu() {
        initComponents();
    }

    public VentanaMenu(Empresa miEmpresa) {
        initComponents();
        this.empresa = miEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonPiloto = new javax.swing.JButton();
        BotonTecnico = new javax.swing.JButton();
        BotonProducto = new javax.swing.JButton();
        BotonFumigacion = new javax.swing.JButton();
        BotonConsulta = new javax.swing.JButton();
        BotonArchivo = new javax.swing.JButton();
        BotonTerminar = new javax.swing.JButton();
        LblMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BotonPiloto.setText("Alta De Piloto");
        BotonPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPilotoActionPerformed(evt);
            }
        });

        BotonTecnico.setText("Alta De Técnico");
        BotonTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTecnicoActionPerformed(evt);
            }
        });

        BotonProducto.setText("Alta De Producto");
        BotonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductoActionPerformed(evt);
            }
        });

        BotonFumigacion.setText(" Registro De Fumigación Individual");
        BotonFumigacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFumigacionActionPerformed(evt);
            }
        });

        BotonConsulta.setText("Consulta");
        BotonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaActionPerformed(evt);
            }
        });

        BotonArchivo.setText(" Carga De Fumigaciones De Archivo");
        BotonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArchivoActionPerformed(evt);
            }
        });

        BotonTerminar.setText("Terminar");
        BotonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTerminarActionPerformed(evt);
            }
        });

        LblMenu.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonFumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(LblMenu)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LblMenu)
                .addGap(18, 18, 18)
                .addComponent(BotonPiloto)
                .addGap(18, 18, 18)
                .addComponent(BotonTecnico)
                .addGap(18, 18, 18)
                .addComponent(BotonProducto)
                .addGap(18, 18, 18)
                .addComponent(BotonFumigacion)
                .addGap(18, 18, 18)
                .addComponent(BotonConsulta)
                .addGap(18, 18, 18)
                .addComponent(BotonArchivo)
                .addGap(18, 18, 18)
                .addComponent(BotonTerminar)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPilotoActionPerformed
        // Se abre la ventana de registro de pilotos
        VentanaPiloto ventana = new VentanaPiloto(this.empresa);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonPilotoActionPerformed

    private void BotonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTerminarActionPerformed
       //Guardamos los datos 
        try{
            try (ObjectOutputStream out = new ObjectOutputStream(Files.newOutputStream(Paths.get("Saves.txt")))) {
                out.writeObject(this.empresa);
            }
        }catch (IOException e){
            System.exit(1);
        }
        System.exit(0);
    }//GEN-LAST:event_BotonTerminarActionPerformed

    private void BotonTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTecnicoActionPerformed
        // Se abre la ventana de registro de tecnicos
        VentanaTecnico ventana = new VentanaTecnico(this.empresa);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonTecnicoActionPerformed

    private void BotonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProductoActionPerformed
        // Se abre la ventana de registro de productos
        VentanaProducto ventana = new VentanaProducto(this.empresa);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonProductoActionPerformed

    private void BotonFumigacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFumigacionActionPerformed
        // Se abre la ventana de registro de fumigaciones individuales
        VentanaFumigacion ventana = new VentanaFumigacion(empresa);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonFumigacionActionPerformed

    private void BotonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaActionPerformed
        // Se abre la ventana de matriz de consulta
        ventanaMatriz ventana = new ventanaMatriz(empresa);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonConsultaActionPerformed

    private void BotonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArchivoActionPerformed
        // Se abre la ventana para cargar fumigaciones desde un archivo
        VentanaCargaFumigacionesDeArchivo ventana = new VentanaCargaFumigacionesDeArchivo(this.empresa);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonArchivoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       //Guardamos los datos en caso de que el usuario cierre el programa sin apretar el boton terminar
       try{
           try (ObjectOutputStream out = new ObjectOutputStream(Files.newOutputStream(Paths.get("Saves.txt")))) {
               out.writeObject(this.empresa);
           }
        }catch (IOException e){
            System.exit(1);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonArchivo;
    private javax.swing.JButton BotonConsulta;
    private javax.swing.JButton BotonFumigacion;
    private javax.swing.JButton BotonPiloto;
    private javax.swing.JButton BotonProducto;
    private javax.swing.JButton BotonTecnico;
    private javax.swing.JButton BotonTerminar;
    private javax.swing.JLabel LblMenu;
    // End of variables declaration//GEN-END:variables
}
